code/foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path
from django.views.generic import RedirectView

handler404 = "snot.views.page_not_found" # noqa
handler500 = "snot.views.server_error" # noqa


urlpatterns = [
    # регистрация и авторизация
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),

    path('', include('snot.urls')),
    path('', include('recipe.urls')),
    path('', include('users.urls')),

    # раздел администратора
    path("admin/", admin.site.urls),

    # flatpages
    path("about/", include("django.contrib.flatpages.urls")),
    path('author/', views.flatpage, {'url': '/author/'}, name='author'),
    path('spec/', views.flatpage, {'url': '/spec/'}, name='spec'),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.png'), name='favicon'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/recipe/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('new-recipe/', views.new_recipe, name='new_recipe'),
    path("follow/", views.follow_view, name="follow_view"),
    path('recipe/<slug>/edit/', views.recipe_edit, name='recipe_edit'),
    path('recipe/<slug>/delete/', views.recipe_delete, name='recipe_delete'),
    path("profile/<username>/", views.profile, name='profile'),
    path('profile/<username>/recipe/<slug>/', views.recipe_view, name='recipe_view'),
    path("favorite/", views.favor_view, name="favor_view"),
    path('shop-list/', views.shop_list, name='shop-list'),
   # path('download', views.download, name='download'),
]

code/snot/urls.py
from django.urls import path

from . import views

urlpatterns = [
     path(
          "ingredients/",
          views.get_ingredients,
          name="get_ingredients"
     ),
     path(
          "subscriptions",
          views.follow,
          name="follow"
     ),
     path(
          "subscriptions/<int:follow_pk>",
          views.unfollow,
          name="unfollow"
     ),
     path(
          "favorites",
          views.in_favor,
          name="in_favor"
     ),
     path(
          "favorites/<int:favor_pk>",
          views.out_favor,
          name="out_favor"
     ),
     path(
          "purchases",
          views.in_list,
          name="in_list"
     ),
     path(
          "purchases/<int:purch_pk>",
          views.out_list,
          name="out_list"
     ),
     path(
          "download",
          views.download,
          name="download"
     ),
]

code/recipe/models.py
from django.contrib.auth import get_user_model
from django.db import models
from slugify import slugify

User = get_user_model()


class Keyword(models.Model):
    title = models.CharField("Ключевое слово", max_length=10)
    value = models.CharField("Значение тега", max_length=10)
    color = models.CharField("Цвет", max_length=10, null=True)

    class Meta:
        verbose_name = u"Тег"
        verbose_name_plural = u"Теги"
        ordering = ["pk"]

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    title = models.CharField(
        "Название ингредиента", max_length=100, null=True, blank=True
    )
    unit = models.CharField("Еденица измерения", max_length=10, null=True, blank=True)

    class Meta:
        verbose_name = u"Ингредиент"
        verbose_name_plural = u"Ингредиенты"
        ordering = ["title"]

    def __str__(self):
        return self.title


class Time(models.Model):
    unit = models.CharField(max_length=10, verbose_name=u"Еденица измерения")
    reduction = models.CharField(max_length=5, verbose_name=u"Сокращение")

    class Meta:
        verbose_name = u"Время"
        verbose_name_plural = u"Время"
        ordering = ["pk"]

    def __str__(self):
        return self.reduction


class Recipe(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="cook", verbose_name=u"Автор"
    )
    title = models.CharField("Название рецепта", max_length=100)
    image = models.ImageField(upload_to="recipes/")
    description = models.TextField("Описание")
    ingredient = models.ManyToManyField(
        Ingredient, through="AmountIngredients", through_fields=("recipe", "ingredient")
    )
    tag = models.ManyToManyField(Keyword, verbose_name=u"Теги")
    cooking_time = models.IntegerField("Время приготовления")
    unit_of_time = models.ForeignKey(
        Time,
        on_delete=models.CASCADE,
        related_name="unit_of_time",
        verbose_name=u"Еденица времени",
    )
    slug = models.SlugField("Ссылка", unique=True)
    pub_date = models.DateTimeField("Дата публикации", auto_now_add=True)

    class Meta:
        verbose_name = u"Рецепт"
        verbose_name_plural = u"Рецепты"
        ordering = ["-pub_date"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
        Slugify name if it doesn't exist. IMPORTANT: doesn't check to see
        if slug is a dupe!
        """
        numb = Recipe.objects.count()+1
        if not self.slug:
            self.slug = f"{numb}-{slugify(self.title)}"
        super(Recipe, self).save(*args, **kwargs)


class AmountIngredients(models.Model):
    amount = models.IntegerField("Дозировка")
    ingredient = models.ForeignKey(
        Ingredient,
        on_delete=models.CASCADE,
        related_name="ingredient",
        verbose_name=u"Ингредиент",
    )
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, verbose_name=u"Блюдо")

    class Meta:
        verbose_name = u"Дозировка"
        verbose_name_plural = u"Дозировка"
        ordering = ["recipe", "pk"]

    def __str__(self):
        return self.ingredient.unit


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="follower")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")


class Favorites(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="favor_by")
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="favor")

    def __str__(self):
        return self.recipe.title


class Shopping(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="shopper")
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="for_list"
    )

    def __str__(self):
        return self.recipe.title

code/recipe/forms.py
from django.forms import CheckboxSelectMultiple, ModelForm
from django.core.exceptions import ValidationError
from recipe.models import Recipe, Ingredient


class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ('title', 'image', 'tag', 'cooking_time', 'unit_of_time', 'description')
        widgets = {
            'tag': CheckboxSelectMultiple(),
        }

    def clean(self):
        known_ids = []
        for items in self.data.keys():
            if 'nameIngredient' in items:
                name, id = items.split('_')
                known_ids.append(id)
        for id in known_ids:
            title = self.data.get(f'nameIngredient_{id}'),
            unit = self.data.get(f'unitsIngredient_{id}')
            ingredient_exists = Ingredient.objects.filter(
                title=title[0],
                unit=unit,
            ).exists()
            if not ingredient_exists:
                raise ValidationError('Выберите ингредиент из списка!')

code/recipe/views.py
import os
from pathlib import Path

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from .forms import RecipeForm
from .models import (AmountIngredients, Follow, Ingredient, Keyword, Recipe,
                     Shopping, Time, User)
from .utils import get_ingredients_list, get_tags_for_edit


def index(request):
    tag = request.GET.getlist('filters')
    recipe_list = Recipe.objects.all()
    if tag:
        recipe_list = recipe_list.filter(tag__value__in=tag).distinct().all()
    paginator = Paginator(recipe_list, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'index.html',
        {'page': page, 'paginator': paginator, }
    )


def profile(request, username):
    profile = get_object_or_404(User, username=username)
    tag = request.GET.getlist('filters')
    recipe_list = Recipe.objects.filter(author=profile.pk).all()
    if tag:
        recipe_list = recipe_list.filter(tag__value__in=tag)
    paginator = Paginator(recipe_list, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'profile.html',
        {
            'profile': profile,
            'recipe_list': recipe_list,
            'page': page,
            'paginator': paginator
        }
    )


def recipe_view(request, slug, username):
    recipe = get_object_or_404(Recipe, slug=slug)
    profile = get_object_or_404(User, username=username)
    return render(
        request,
        'recipe.html',
        {'profile': profile, 'recipe': recipe, }
    )


@login_required
def new_recipe(request):
    user = User.objects.get(username=request.user)
    form = RecipeForm(
        request.POST or None,
        files=request.FILES or None)
    if request.method == 'POST':
        ingredients = get_ingredients_list(request)
        if not ingredients:
            form.add_error(None, 'Добавьте ингредиенты')
        elif form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = user
            recipe.save()
            for ing_title, amount in ingredients.items():
                ingredient = get_object_or_404(Ingredient, title=ing_title)
                recipe_ing = AmountIngredients(
                    recipe=recipe,
                    ingredient=ingredient,
                    amount=amount
                )
                recipe_ing.save()
            form.save_m2m()
            return redirect('index')
    else:
        form = RecipeForm()
    return render(request, 'new_recipe.html', {'form': form})


@login_required
def recipe_edit(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug)
    if request.user != recipe.author:
        return redirect('recipe', slug=slug)

    form = RecipeForm(
        request.POST or None,
        files=request.FILES or None,
        instance=recipe
    )
    if request.method == "POST":
        ingredients = get_ingredients_list(request)
        if not ingredients:
            form.add_error(None, 'Добавьте ингредиенты')
        if form.is_valid():
            form.save()
            AmountIngredients.objects.filter(recipe=recipe).delete()

            for ing_title, amount in ingredients.items():
                ingredient = get_object_or_404(Ingredient, title=ing_title)
                recipe_ing = AmountIngredients(
                    recipe=recipe,
                    ingredient=ingredient,
                    amount=amount
                )
                recipe_ing.save()
            return redirect('recipe_view', username=request.user.username, slug=recipe.slug)

    all_tags = recipe.tag.values_list('value', flat=True)
    all_ingredients = AmountIngredients.objects.filter(recipe=recipe.id)

    return render(request, 'change_recipe.html', {
        'form': form,
        'recipe': recipe,
        'all_tags': all_tags,
        'all_ingredients': all_ingredients,
    })


@login_required
def recipe_delete(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug)
    path = str(recipe.image)
    os.remove(f'{Path(__file__).resolve(strict=True).parent.parent}/media/{path}')
    recipe.delete()
    return redirect("index")


@login_required
def follow(request, username):
    author = get_object_or_404(User, username=username)
    user = get_object_or_404(User, username=request.user)
    follow_count = Follow.objects.filter(user=request.user, author=author).count()
    if user != author and follow_count == 0:
        Follow.objects.create(user=user, author=author)
        return redirect('profile', username=username)
    return redirect('profile', username=username)


@login_required
def follow_view(request):
    follow = Follow.objects.filter(user=request.user).order_by("author").all()
    paginator = Paginator(follow, 3)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, "follow.html", {"page": page, "paginator": paginator})


@login_required
def favor_view(request):
    tag = request.GET.getlist('filters')
    recipe_list = Recipe.objects.filter(
        favor__user__id=request.user.id).all()
    if tag:
        recipe_list = recipe_list.filter(tag__value__in=tag).distinct().all()

    paginator = Paginator(recipe_list, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    return render(request, 'favorites.html', {
        'page': page,
        'paginator': paginator,
    })


@login_required
def shop_list(request):
    shop_list = Shopping.objects.filter(user=request.user).all()

    return render(request, 'shop_list.html', {
        'page': shop_list,
    })

code/templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        {% load static %}
        {% load recipe_filters %}
        {% csrf_token %}
        {% block static %}
        <link rel="stylesheet" href={% static 'pages/form.css' %}>
        {% endblock %}
        <title>{% block title%}Регистрация{% endblock%} | едадел</title>
    </head>
    <body>
        <header class="header">
            <nav class="nav">
                <div class="nav__container container">
                    {% if user.is_authenticated %}
                    <ul class="nav__items list">
                        {% block index %}<li class="nav__item">{% endblock %}<a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
                        {% block subs %}<li class="nav__item">{% endblock %}<a href="{% url 'follow_view' %}" class="nav__link link">Мои подписки</a></li>
                        {% block new_recipe %}<li class="nav__item">{% endblock %}<a href="{% url 'new_recipe' %}" class="nav__link link">Создать рецепт</a></li>
                        {% block favorites %}<li class="nav__item">{% endblock %}<a href="{% url 'favor_view' %}" class="nav__link link">Избранное</a></li>
                        {% block shop %}<li class="nav__item">{% endblock %}<a href="{% url 'shop-list' %}" class="nav__link link">Список покупок {{ count }}</a>
                        <span  class="badge badge_style_sl nav__badge" id="counter">{{ request|count_list }}</span></li>
                    </ul>
                    <ul class="nav__items list">
                        {% block profile_edit %}<li class="nav__item">{% endblock %}<a href="{% url 'profile_edit' %}" class="nav__link link">Профиль</a></li>
                        {% block pass_change %}<li class="nav__item">{% endblock %}<a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
                        <li class="nav__item"><a href="{% url 'logout'%}" class="nav__link link">Выход</a></li>
                    </ul>
                    {% else %}
                    <ul class="nav__items list">
                        <li class="nav__item nav__item_active"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
                    </ul>
                    <ul class="nav__items list">
                        {% block login %}<li class="nav__item">{% endblock %}<a href="{% url 'login'%}" class="nav__link link">Войти</a></li>
                        {% block create_acc %}<li class="nav__item">{% endblock %}<a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
                    </ul>
                    {% endif %}
                </div>
            </nav>
        </header>
        <main class="main container">
            <div class="container">
                {% block content %}
                <!-- Содержимое страницы -->
                {% endblock content %}
            </div>
        </main>
        {% include 'footer.html' %}
    </body>
</html>

code/templates/favor_item.html
{% load recipe_filters %}
<div class="card" data-id="{{ recipe.id }}">
    <a href="{% url 'recipe_view' recipe.author.username recipe.slug %}" class="link" target="_blank">
        {% load thumbnail %}
        {% thumbnail recipe.image "x240" crop="center" as im %}
        <img src="{{ im.url }}" alt="{{ recipe.title }}" class="card__image">
        {% endthumbnail %}
    </a>
    <div class="card__body">
        <a class="card__title link" href="{% url 'recipe_view' recipe.author.username recipe.slug %}" target="_blank">{{ recipe.title }}</a>
        <ul class="card__items">
            {% for tag in recipe.tag.all %}
            <li class="card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag.title }}</span></li>
            {% endfor %}
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> {{recipe.cooking_time}} {{recipe.unit_of_time.reduction}}</p>
            <p class="card__text"><span class="icon-user"></span> {{ recipe.author.get_full_name }}</p>
        </div>
    </div>
    <div class="card__footer">
        {% if recipe|is_shopping:user %}
        <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span>Рецепт добавлен</button>
        {% else %}
        <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
        {% endif %}
        <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
    </div>
</div>

code/templates/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'index' %}" class="footer__brand link">Поваренная книга</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'author' %}" class="footer__link link">Об авторе</a></li>
            <li class="footer__item"><a href="{% url 'spec' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

code/templates/new_recipe.html
{% extends 'base.html' %}
{% block title%} Добавить рецепт {% endblock%}
    {% load static %}
    {% block new_recipe %} <li class="nav__item nav__item_active"> {% endblock %}
    {% csrf_token %}
        {% load static %}
        {% block static %}
        <link rel="stylesheet" href={% static 'pages/form.css' %}>
        {% endblock %}
{% load user_filters %}
{% block content %}
<div class="main__header">
    <h1 class="main__title">Добавить рецепт</h1>
</div>
<div class="form-container">
    <form class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form__group">
            <label for="{{ form.title.id_for_label }}" class="form__label">Название рецепта</label>
            <div class="form__field-group">
                {{ form.title|addclass:"form__input" }}
                {% if form.errors %}
                    {% for error in form.title.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form__group">
            <p class="form__label">Теги</p>
            <div class="form__field-group">
                <div class="tags">
                    {% for tag_choice, tag_value in form.tag.field.choices %}
                        <div class="tags__item">
                            <input 
                                type="checkbox" 
                                name="tag" 
                                value="{{ tag_choice.instance.pk }}"
                                id="id_{{ tag_choice.instance.value }}" 
                                class="tags__checkbox tags__checkbox_style_{{ tag_choice.instance.color }}">
                                <label for="id_{{ tag_choice.instance.value }}" class="tags__label">{{ tag_choice.instance.title }}</label>
                        </div>
                    {% endfor %}
                </div>
                {% if form.errors %}
                    {% for error in form.tag.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form__group">
            <label for="nameIngredient" class="form__label">Ингредиенты</label>
            <div class="form__field-group">
                <div class="form__field-group-ingredientes">
                    <div class="form__dropdown">
                        <input type="text" id="nameIngredient" class="form__input">
                        <div class="form__dropdown-items"></div>
                    </div>
                    <input type="number" id="cantidad" class="form__input" min="0">
                    <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                </div>
                <div class="form__field-group-ingredientes-container">
                    {% if all_ingredients %}
                        {% for ing in all_ingredients %}
                        <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}"><span>
                                {{ ing.ingredient.title }} {{ ing.amount }}
                                {{ ing.ingredient.unit }}</span> <span
                                class="form__field-item-delete"></span>
                            <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient_{{ forloop.counter }}"
                                type="hidden" value="{{ ingredient.ingredient.title }}">
                            <input id="valueIngredient_{{ forloop.counter }}"
                                name="valueIngredient_{{ forloop.counter }}" type="hidden"
                                value="{{ ingredient.count }}">
                            <input id="unitsIngredient_{{ forloop.counter }}"
                                name="unitsIngredient_{{ forloop.counter }}" type="hidden"
                                value="{{ ingredient.ingredient.dimension }}">
                        </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                {% if form.errors %}
                {% for error in field.errors %}
                    <span class="form__error">{{ error|escape }}</span>
                {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form__group">
            <label for="{{ form.cooking_time.id_for_label }}" class="form__label">Время приготовления</label>
            <div class="form__field-group form__field-group_time">
                {{ form.cooking_time|addclass:"form__input" }}
                {{ form.unit_of_time|addclass:"form__input" }}
                {% if form.errors %}
                    {% for error in field.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form__group">
            <label for="{{ form.description.id_for_label }}" class="form__label">Описание</label>
            <div class="form__field-group">
                {{ form.description|addclass:"form__textarea" }}
                {% if form.errors %}
                    {% for error in field.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form__group">
            <span class="form__label">Загрузить фото</span>
            <div class="form__field-group">
                {{ form.image.as_hidden }}
                <label for="id_image" class="form__file-button">Выберите файл</label>
                <span id="file-chosen" style="margin-left: 0.3rem; font-family: 'Montserrat', sans-serif;">Изображение не выбрано</span>
                {% if form.errors %}
                    {% for error in field.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        {% if form.errors %}
            {% for error in form.non_field_errors %}
            <div class="form__group">
                <span class="form__error">{{ error|escape }}</span>
            </div>
            {% endfor %}
        {% endif %}
        <div class="form__footer">
            <button class="button button_style_blue">Создать рецепт</button>
        </div>
        </form>
    </div>

<script>
    const actualBtn = document.getElementById('id_image');
    const fileChosen = document.getElementById('file-chosen');
    actualBtn.addEventListener('change', function(){
        fileChosen.textContent = this.files[0].name
    })
</script>
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/utils/debouncing.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/project/formRecipe.js' %}"></script>
{% endblock %}

code/templates/recipe.html
{% extends 'base.html' %}
{% block title%} {{ recipe.title }} {% endblock%}
    {% load static %}
    {% load recipe_filters %}
    {% csrf_token %}
    {% block static %}
    <link rel="stylesheet" href="{% static 'pages/single.css' %}">
    {% endblock %}
    {% block content %}
        <div class="single-card" data-id="{{ recipe.id }}" data-author="{{ profile.id }}">
            <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" class="single-card__image">
            <div class="single-card__info">
                <div class="single-card__header-info">
                    <h1 class="single-card__title"> {{ recipe.title }} </h1>
                    {% if user.is_authenticated %}
                    <div class="single-card__favorite">
                        {% if recipe|is_favorite:user %}
                        <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
                        {% else %}
                        <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
                        {% endif %}
                    </div>
                    {% endif %}
                </div>
                <ul class="single-card__items">
                    {% for tag in recipe.tag.all %}
                    <li class="single-card__item">
                        <span class="badge badge_style_{{ tag.color }}">{{ tag.title }}</span></li>
                    </li>
                    {% endfor %}
                </ul>
                <div class="single-card__items single-card__items_column">
                    <p class="single-card__text"><span class="icon-time"></span> {{recipe.cooking_time}} {{recipe.unit_of_time.reduction}}</p>
                    <ul class="single-card__items">
                        <li class="single-card__item">
                                <span class="icon-user"></span>
                                <a href="{% url 'profile' recipe.author.username %}" class="single-card__text">{{ recipe.author.get_full_name }}</a>
                        </li>
                        {% if user == recipe.author %}
                        <li class="single-card__item"> <a style="margin-left: 2.5em" href="{% url 'recipe_edit' recipe.slug %}"
                                class="single-card__text">Редактировать рецепт</a></li>
                        {% endif %}
                    </ul>
                </div>
                {% if user.is_authenticated %}
                <ul class="single-card__items">
                    <li class="single-card__item">
                        {% if recipe|is_shopping:user %}
                        <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span>Рецепт добавлен</button>
                        {% else %}
                        <button class="button button_style_blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
                        {% endif %}
                    </li>
                    {% ifnotequal user.username recipe.author.username %}
                    <li class="single-card__item">
                        {% if recipe.author|is_follow:user%}
                        <button class="button button_style_light-blue" name="subscribe">Отписаться от автора</button>
                        {% else %}
                        <button class="button button_style_light-blue" name="subscribe" data-out>Подписаться на автора</button>
                        {% endif %}
                    </li>
                    {% endifnotequal %}
                </ul>
                {% endif %}
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Ингредиенты:</h3>
                    <div class="single-card__items single-card__items_column">
                        {% for ing in recipe.amountingredients_set.all %}
                        {% if ing.amount != 0 %}
                        <p class="single-card__section-item">{{ ing.ingredient.title }} - {{ ing.amount }} {{ ing.ingredient.unit }}</p>
                        {% else %}
                        <p class="single-card__section-item">{{ ing.ingredient.title }} - по вкусу</p>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Описание:</h3>
                    <p class="single-card__section-text">{{ recipe.description }}</p>
                </div>
            </div>
        </div>
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/SingleCard.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    {% if user.is_authenticated %}
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/project/singlePage.js' %}"></script>
    {% else %}
    <script src="{% static 'js/project/singlePageNotAuth.js' %}"></script>
    {% endif %}
{% endblock %}